@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxNjFhZjEwLTAyNTQtNDQxMS1iNzgwLWYxOTgxMzJkNDA2MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1bHRhbjdAZG9tYWluLmNvbSIsImV4cCI6MTc4NDQwOTMzNywiaXNzIjoiU2hlaHJ5YXJCYW5raW5nQXBwIiwiYXVkIjoiU2hlaHJ5YXJCYW5raW5nQXBwQ2xpZW50cyJ9.jm6gtMmgDNdmz6w-psjVVj5_kWBoQ4rrNDP0yhyH7pg


###
POST http://localhost:5196/register
Content-Type: application/json

{
    "fullName": "Sultan7",
    "email": "sultan7@domain.com",
    "password": "Abcd1234!"
}

###
POST http://localhost:5196/login
Content-Type: application/json

{
    "email": "sultan7@domain.com",
    "password": "Abcd1234!"
}

###
POST http://localhost:5196/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "accountType": 0
}

###
GET http://localhost:5196/accounts
Authorization: Bearer {{token}}

###
GET http://localhost:5196/accounts/26cb8e69-6269-4b05-86de-839bdef93085
Authorization: Bearer {{token}}


###
POST http://localhost:5196/accounts/26cb8e69-6269-4b05-86de-839bdef93085/deposit
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "amount": 100000
}

###
POST http://localhost:5196/accounts/26cb8e69-6269-4b05-86de-839bdef93085/withdraw
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "amount": 10000
}

###
POST http://localhost:5196/accounts/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fromAccountNumber": "PK-001-0910713333",
    "toAccountNumber": "PK-001-0545511956",
    "amount": 3200
}

###
GET http://localhost:5196/accounts/PK-001-0910713333/transactions?page=1&pageSize=5
Authorization: Bearer {{token}}